
POST   https://glis-backend.onrender.com/api/user/add
Content-Type: application/json
   
{
    "Usr_name":"admin",
    "Usr_email":"admin@example.com",
    "Usr_phone":"123",
    "Usr_address":"sathy",
    "Usr_pass":"1234",
    "role":"Farmer"
}


